### ISSUE TITLE
Error in levela, levelb, levelc

### ISSUE THREAD

**Issue by SamCrofts** [economicanalysiswithmatrices/Zombie-RPG#11]
While testing my code, i was realising that the variables zombiehealth and playerhealth were not behaving as they should.
Open homescreen.m, levela , levelb and levelc

1. Run homescreen.m
2. play game on hard difficulty as it is easier to see the problems on this difficulty
3. On a correct answer, you gain 20HP, on an incorrect answer, the zombie gains 20HP
4. Every round the dice is rolled, if you win, zombie takes 20 damage, if zombie wins, zombie takes 20 damage, on a draw, no one takes any damage.
5. Sometimes on draws, zombie is taking damage when it is not supposed to
6. Sometimes between screens, it is not calculating the player health and zombie health correctly and isn't the value it should be at certain stages.

The correct answers are A - B - B so far

**Comment by meleantonio** [comment]
@SamCrofts is this in the master branch?

**Comment by SamCrofts** [comment]
yes

> @SamCrofts is this in the master branch?

yes

**Comment by meleantonio** [comment]
@SamCrofts one thing that I can see is that you are using global variables. This is deprecated. You should instead set handles with the function set (as you actually do for a bit) instead of using global variables. That most likely would solve the problem? So instead of updating zombiehealth, get the value of zombiehealthtag with get(......) and then set it to a new value with set(.....)

Also, I noticed that there are several levels missing from the game (levelg, levelim etc) so the game crashes at some point.

**Comment by SamCrofts** [comment]
surely i need them to be global variables in order to transfer across m files

The levels are missing because i haven't created them yet

**Comment by meleantonio** [comment]
mmm I see... another thing that I noticed is that you close the levels before updating the health variables. You should do the opposite, first update the global variable, then close the level.

**Comment by SamCrofts** [comment]
tried that, still doesn't fix the issue.

**Comment by meleantonio** [comment]
no idea.

**Comment by SamCrofts** [comment]
Well, what could i do instead of using global variables, if that is the problem?

**Comment by SamCrofts** [comment]
sorted by using one GUI

**Comment by meleantonio** [comment]
@SamCrofts just saw this, well done.
